apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: yuwonopipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yuwonopipelinesjavascriptdocker 
    spec:
      containers:
        - name: yuwonopipelinesjavascriptdocker 
          image: testk8s.azurecr.io/yuwonopipelinesjavascriptdocker
          ports:
          - containerPort: 8080